# Generated by Django 4.1.13 on 2025-08-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tags'),
    ]

    operations = [
    ]
