# Generated by Django 4.1.13 on 2025-08-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail image for this post', null=True, upload_to='post_thumbnails/'),
        ),
    ]
